# Generated by Django 6.0.6 on 2026-06-28 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_game_image_game_is_active_alter_rate_mark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='image',
            new_name='icon',
        ),
        migrations.AddField(
            model_name='game',
            name='game_link',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='site_url_name',
            field=models.CharField(default='example.com', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
